name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y g++ gcovr

    - name: Build
      run: g++ -fprofile-arcs -ftest-coverage bmi_calculator.cpp -o bmi_calculator

    - name: Run tests
      run: ./bmi_calculator.cpp

    - name: Generate coverage report
      run: gcovr -r . --xml -o coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

